package Reposes; 


import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;
import maper.IMapResultSetIntoEntity;
import baza.IUnitOfWork;
import rezervations.Guest;

public class R_guest extends RepositoryBase<Guest>
implements IR_guest { 
	
	
	public R_guest(Connection connection,
			IMapResultSetIntoEntity<Guest> mapper,
			IUnitOfWork uow) {
			super(connection, mapper,uow);
			}
	
	
	protected String tableName() {
		return "Guest";
	}
	protected String createTableSql() {
		return "CREATE TABLE Guest("
		+ "id bigint GENERATED BY DEFAULT AS IDENTITY,"
		+ "name VARCHAR(20),"
		+ "surname VARCHAR(50)"
		+ ")";
	}
	protected String insertSql() {
		return "INSERT INTO Guest(name,surname) VALUES(?,?)";
	}
	protected String updateSql() {
		return "UPDATE Guest set name=?, surname=? WHERE id=?";
	}
	
	protected void setupInsert(Guest entity) throws SQLException {
		insert.setString(1, entity.getName());
		insert.setString(2, entity.getSurname());
	}
	
	protected void setupUpdate(Guest entity) throws SQLException {
		update.setString(1, entity.getName());
		update.setString(2, entity.getSurname());

		update.setLong(3, entity.getId());

		update.setLong(3, entity.getId());

	}



	public rezervations.Guest get(long g_id) {
		// TODO Auto-generated method stub
		return null;
	}


	public List<rezervations.Guest> getAll() {
		// TODO Auto-generated method stub
		return null;
	}


	public void add(rezervations.Guest entity) {
		// TODO Auto-generated method stub
		
	}


	public void update(rezervations.Guest entity) {
		// TODO Auto-generated method stub
		
	}


	public void delete(rezervations.Guest entity) {
		// TODO Auto-generated method stub
		
	}


	public List<rezervations.Guest> withName(String name) {
		// TODO Auto-generated method stub
		return null;
	}


	public int getMaxId() {
		// TODO Auto-generated method stub
		return 0;
	}

}
