package Reposes; 


import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;
import maper.IMapResultSetIntoEntity;
import baza.IUnitOfWork;
import rezervations.Guest;

public class R_guest { 
	
	
	public PersonRepository(Connection connection,
			IMapResultSetIntoEntity<Person> mapper,
			IUnitOfWork uow) {
			super(connection, mapper,uow);
			}
	
	
	protected String tableName() {
		return "person";
	}
	protected String createTableSql() {
		return "CREATE TABLE person("
		+ "id bigint GENERATED BY DEFAULT AS IDENTITY,"
		+ "name VARCHAR(20),"
		+ "surname VARCHAR(50)"
		+ ")";
	}
	protected String insertSql() {
		return "INSERT INTO person(name,surname) VALUES(?,?)";
	}
	protected String updateSql() {
		return "UPDATE PERSON set name=?, surname=? WHERE id=?";
	}
	
	protected void setupInsert(Guest entity) throws SQLException {
		insert.setString(1, entity.getName());
		insert.setString(2, entity.getSurname());
	}
	
	protected void setupUpdate(Guest entity) throws SQLException {
		update.setString(1, entity.getName());
		update.setString(2, entity.getSurname());
		update.setInt(3, entity.getId());
	}
	public <Guest> List<Guest> withName(String name) {
	// TODO Auto-generated method stub
	return null;
	}

}
