package Reposes;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;

import maper.Guest_Maper;
import baza.IUnitOfWork;
import rezervations.Rezervation;
import rezervations.Guest; 
import maper.Rezervation_Mapper;

public class R_Rez extends RepositoryBase<Rezervation>
	implements IR_Rez{
	
	public R_Rez(Connection connection, 
			Rezervation_Mapper mapper,
			IReposytory<Guest> GuestRepo,IUnitOfWork uow) {
		super(connection, mapper,uow);
		mapper.setGuestRepo(GuestRepo);	
	}
	
	@Override
	protected String tableName() {
		// TODO Auto-generated method stub
		return "Rezervation";
	}
	@Override
	protected String createTableSql() {
		// TODO Auto-generated method stub
		return "CREATE TABLE Rezervation("
				+ "id bigint GENERATED BY DEFAULT AS IDENTITY,"
				+ "Guest_id INT,"
				+ "naleznosc INT," 
				+ "currency VARCHAR(20),"
				+ ")";
	}
	@Override
	protected String insertSql() {
		// TODO Auto-generated method stub
		return "INSERT INTO Rezervation(Guest_id, amount, currency) VALUES (?, ?, ?)";
	}
	@Override
	protected String deleteSql() {
		// TODO Auto-generated method stub
		return "DELETE FROM Rezervation WHERE ID = ?";
	}
	@Override
	protected String updateSql() {
		// TODO Auto-generated method stub
		return "UPDATE Rezervation SET Guest_id = ?, amount = ?, currency = ? WHERE ID = ?";
	}
	@Override
	protected String selectByIdSql() {
		// TODO Auto-generated method stub
		return "SELECT * FROM Rezervation WHERE id=?";
	}
	@Override
	protected String selectAllSql() {
		// TODO Auto-generated method stub
		return "SELECT * FROM Rezervation";
	}
	
	@Override
	protected void setupInsert(Rezervation entity) throws SQLException {
		insert.setDouble(1, entity.getNaleznosc());
		insert.setString(2, entity.StartToString());
		insert.setString(2, entity.EndToString());
		update.setLong(3, entity.getNr_k());
		
	}

	@Override
	protected void setupUpdate(Rezervation entity) throws SQLException {
		update.setInt(1, entity.getNaleznosc());
		update.setString(2, entity.StartToString());
		update.setString(2, entity.EndToString());
		update.setLong(3, entity.getNr_k());

}

	public List<Rezervation> byGuest(Guest Guest) {
		// TODO Auto-generated method stub
		return null;
	}

	public void add(Guest entity) {
		// TODO Auto-generated method stub
		
	}

	public void update(Guest entity) {
		// TODO Auto-generated method stub
		
	}

	public void delete(Guest entity) {
		// TODO Auto-generated method stub
		
	}

	public int getMaxId() {
		// TODO Auto-generated method stub
		return 0;
	}

	public Rezervation get(long g_id) {
		// TODO Auto-generated method stub
		return null;
	}

	public List<Rezervation> byPerson(Guest guest) {
		// TODO Auto-generated method stub
		return null;
	}
}